/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de.buw.se4de;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author nikhi
 */
public class home extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton newStudentBtn;
    public JButton newBookBtn;
    public JButton statisticsBtn;
    public JButton issueBookBtn;
    public JButton returnBookBtnActionPerformed;
    public JButton loginBtn;
    public JButton logoutBtn;
    
    public static boolean isActiveSession = true;
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        newStudentBtn = new javax.swing.JButton();
        newBookBtn = new javax.swing.JButton();
        statisticsBtn = new javax.swing.JButton();
        issueBookBtn = new javax.swing.JButton();
        returnBookBtnActionPerformed = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newStudentBtn.setText("New Student");
        newStudentBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newStudentBtnActionPerformed(evt);
            }
        });

        newBookBtn.setText("New Book");
        newBookBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newBookBtnActionPerformed(evt);
            }
        });

        statisticsBtn.setText("Statistics");
        statisticsBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                statisticsBtnActionPerformed(evt);
            }
        });

        issueBookBtn.setText("Issue Book");
        issueBookBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                issueBookBtnActionPerformed(evt);
            }
        });

        returnBookBtnActionPerformed.setText("Return Book");
        returnBookBtnActionPerformed.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                returnBookBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        
        loginBtn.setText("Login");
        loginBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        //layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(31, 31, 31).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(newStudentBtn).addComponent(returnBookBtnActionPerformed)).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(85, 85, 85).addComponent(logoutBtn)).addGroup(layout.createSequentialGroup().addGap(67, 67, 67).addComponent(newBookBtn).addGap(70, 70, 70).addComponent(statisticsBtn).addGap(52, 52, 52).addComponent(issueBookBtn))).addContainerGap(311, Short.MAX_VALUE)));
        //layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(24, 24, 24).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(newStudentBtn).addComponent(newBookBtn).addComponent(statisticsBtn).addComponent(issueBookBtn)).addGap(54, 54, 54).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(returnBookBtnActionPerformed).addComponent(logoutBtn)).addContainerGap(335, Short.MAX_VALUE)));
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup().addGap(31, 31, 31)
        		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(newStudentBtn).addComponent(returnBookBtnActionPerformed))
        		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup().addGap(82, 82, 82).addComponent(loginBtn).addGap(80, 80, 80).addComponent(logoutBtn))
        		.addGroup(layout.createSequentialGroup().addGap(67, 67, 67).addComponent(newBookBtn).addGap(70, 70, 70).addComponent(statisticsBtn).addGap(52, 52, 52).addComponent(issueBookBtn))).addContainerGap(200, Short.MAX_VALUE)));
        
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
        		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(newStudentBtn).addComponent(newBookBtn).addComponent(statisticsBtn).addComponent(issueBookBtn)).addGap(54, 54, 54)
        		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(returnBookBtnActionPerformed) .addComponent(loginBtn)).addComponent(logoutBtn)));

        pack();

        this.setTitle("Home Page");
        this.setSize(600, 300);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }// </editor-fold>//GEN-END:initComponents

    
    public void loginBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setVisible(false);
        new login().setVisible(true);
        isActiveSession = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    
    public void logoutBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setVisible(false);
        new login().setVisible(true);
        isActiveSession = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    public void newStudentBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new NewStudent().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void newBookBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new de.buw.se4de.NewBook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void issueBookBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new de.buw.se4de.IssueBook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    public void returnBookBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new de.buw.se4de.ReturnBook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    public void statisticsBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new de.buw.se4de.Statistics().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    // End of variables declaration//GEN-END:variables
}
