 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de.buw.se4de;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author nikhi
 */
public class NewBook extends javax.swing.JFrame {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton saveBtn;
    public JButton closeBtn;
    public JLabel bookIdLabel;
    public JLabel bookTitleLabel;
    public JLabel authorLabel;
    public JLabel priceLabel;
    public JLabel publishingYearLabel;
    public JTextField bookIDTextField;
    public JTextField bookTitleTextField;
    public JTextField authorTextField;
    public JTextField priceTextField;
    public JTextField publishingYearTextField;

    /**
     * Creates new form NewBook
     */

    public NewBook() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        bookIdLabel = new JLabel();
        bookTitleLabel = new JLabel();
        authorLabel = new JLabel();
        priceLabel = new JLabel();
        publishingYearLabel = new JLabel();
        bookIDTextField = new JTextField();
        bookTitleTextField = new JTextField();
        authorTextField = new JTextField();
        priceTextField = new JTextField();
        publishingYearTextField = new JTextField();
        saveBtn = new JButton();
        closeBtn = new JButton();


        bookIdLabel.setText("Book ID");

        bookTitleLabel.setText("Name");

        authorLabel.setText("Publisher");

        priceLabel.setText("Price");

        publishingYearLabel.setText("Publishing Year");

        saveBtn.setText("Save");

        saveBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(143, 143, 143).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(bookIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(bookTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(authorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE).addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(publishingYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)).addGap(112, 112, 112).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(publishingYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(bookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(bookIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))).addGroup(layout.createSequentialGroup().addGap(176, 176, 176).addComponent(saveBtn).addGap(76, 76, 76).addComponent(closeBtn))).addContainerGap(232, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(68, 68, 68).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(bookIdLabel).addComponent(bookIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(22, 22, 22).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(bookTitleLabel).addComponent(bookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(28, 28, 28).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(authorLabel).addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(26, 26, 26).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(priceLabel).addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(27, 27, 27).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(publishingYearLabel).addComponent(publishingYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(57, 57, 57).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(saveBtn).addComponent(closeBtn)).addContainerGap(127, Short.MAX_VALUE)));

        pack();


        this.setSize(500, 500);
        this.setResizable(false);
        this.setTitle("New Book");
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(saveBtn);

    }// </editor-fold>//GEN-END:initComponents

    public void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DBConnection.setBook(bookIDTextField.getText(), bookTitleTextField.getText(), authorTextField.getText(), priceTextField.getText(), publishingYearTextField.getText());
        DBConnection.writeBookInDB();

        //bookIDTextField.setText("");
        //bookTitleTextField.setText("");
        //authorTextField.setText("");
        //priceTextField.setText("");
        //publishingYearTextField.setText("");
        
        //take this information and store it in your data base.
        String a=bookIDTextField.getText();
        String b=bookTitleTextField.getText();
        String c=authorTextField.getText();
        String d=priceTextField.getText();
        String e=publishingYearTextField.getText();
        
        DBConnection.setBook(d, b, a, c, e); //nayeem
        //Book.books.add(new Book(a,b,c,d,e,false));
    }//GEN-LAST:event_jButton1ActionPerformed

    public void closeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }
}
