/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de.buw.se4de;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author nikhi
 */
public class NewSudent extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton saveBtn;
    public JButton closeBtn;
    public JComboBox<String> facultyComboBox;
    public JComboBox<String> choicesComboBox;
    public JLabel studentIDLabel;
    public JLabel nameLabel;
    public JLabel familyNameLabel;
    public JLabel courseNameLabel;
    public JLabel branchNameLabel;
    public JTextField studentIDTextBox;
    public JTextField nameTextBox;
    public JTextField familynameTextBox;

    /**
     * Creates new form newSudent
     */
    public NewSudent() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSudent().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        studentIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        familyNameLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        branchNameLabel = new javax.swing.JLabel();
        studentIDTextBox = new javax.swing.JTextField();
        nameTextBox = new javax.swing.JTextField();
        familynameTextBox = new javax.swing.JTextField();
        facultyComboBox = new javax.swing.JComboBox<>();
        choicesComboBox = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();


        studentIDLabel.setText("Student ID");

        nameLabel.setText("Name");

        familyNameLabel.setText("Family Name");

        courseNameLabel.setText("Course Name");

        branchNameLabel.setText("Branch Name");

        facultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Faculty Of Media"}));

        choicesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"CSDM", "Digital Engineering"}));

        saveBtn.setText("Save"); //TODO Connect to a database, this button isn't doing anything
        saveBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        closeBtn.setText("Close");
        closeBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(familyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup().addGap(168, 168, 168).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(studentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(branchNameLabel).addComponent(courseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))).addGap(118, 118, 118).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(studentIDTextBox, javax.swing.GroupLayout.Alignment.LEADING).addComponent(nameTextBox, javax.swing.GroupLayout.Alignment.LEADING).addComponent(familynameTextBox, javax.swing.GroupLayout.Alignment.LEADING).addComponent(facultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(choicesComboBox, 0, 200, Short.MAX_VALUE))).addGroup(layout.createSequentialGroup().addGap(212, 212, 212).addComponent(saveBtn).addGap(135, 135, 135).addComponent(closeBtn))).addContainerGap(75, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(93, 93, 93).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(studentIDLabel).addComponent(studentIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nameLabel).addComponent(nameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(familyNameLabel).addComponent(familynameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(courseNameLabel).addComponent(facultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(branchNameLabel).addComponent(choicesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(40, 40, 40).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(saveBtn).addComponent(closeBtn)).addContainerGap(59, Short.MAX_VALUE)));

        pack();

        this.setTitle("Create New Student");
        this.setLocationRelativeTo(null);
        this.setSize(600, 500);
        this.getRootPane().setDefaultButton(saveBtn);

    }// </editor-fold>//GEN-END:initComponents

    public void closeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }
    //GEN-LAST:event_jButton2ActionPerformed
    // End of variables declaration//GEN-END:variables

    public void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        studentIDTextBox.setText("");
        nameTextBox.setText("");
        familynameTextBox.setText("");
    }
}
