/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de.buw.se4de;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;

/**
 * @author nikhi
 */
public class Statistics extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton closeBtn;
    private JLabel issueDetailsLabel;
    private JLabel returnDetailsLabel;
    private JScrollPane issueDetailsScPane;
    private JScrollPane returnDetailsScPane;
    private JTable issueDetailsTable;
    private JTable returnDetailsTable;

    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        issueDetailsLabel = new JLabel();
        issueDetailsScPane = new JScrollPane();
        issueDetailsTable = new JTable();
        returnDetailsLabel = new JLabel();
        returnDetailsScPane = new JScrollPane();
        returnDetailsTable = new JTable();
        closeBtn = new JButton();
        
        
        issueDetailsLabel.setText("Issue Details");

        String[] columNames = {"Book ID", "Book Title", "Author Name", "Price", "Publishing Year"};

        Object[][] dataBase = DBConnection.booksDB;
        DefaultTableModel defTableModel = new DefaultTableModel(dataBase, columNames);
       // System.out.println(defTableModel);
        
        //here you need to put the data that it is stored inside your model. //nayeem
        issueDetailsTable.setModel(defTableModel);
        issueDetailsScPane.setViewportView(issueDetailsTable);
        issueDetailsTable.setEnabled(false);   //nayeem

        returnDetailsLabel.setText("Return details");
        
        
        //here where you should put the information //nayeem
        returnDetailsTable.setModel(new DefaultTableModel(new Object[][]{{null, null, null, null}, {null, null, null, null}, {null, null, null, null}, {null, null, null, null}}, columNames));
        returnDetailsScPane.setViewportView(returnDetailsTable);
        returnDetailsTable.setEnabled(false); //nayeem
        
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(issueDetailsScPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE).addComponent(returnDetailsScPane))).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(339, 339, 339).addComponent(issueDetailsLabel)).addGroup(layout.createSequentialGroup().addGap(356, 356, 356).addComponent(returnDetailsLabel))).addGap(0, 0, Short.MAX_VALUE))).addContainerGap()).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(closeBtn).addGap(326, 326, 326)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(38, 38, 38).addComponent(issueDetailsLabel).addGap(18, 18, 18).addComponent(issueDetailsScPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(returnDetailsLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(returnDetailsScPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(81, 81, 81).addComponent(closeBtn).addContainerGap(147, Short.MAX_VALUE)));

        pack();

        this.setSize(500, 700);
        this.setResizable(false);
        this.setTitle("Statistics");
        this.setLocationRelativeTo(null);




    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    // End of variables declaration//GEN-END:variables
}
